### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by rickyviking** [bjornblissing/osgoculusviewer#88]
After updating to branch 1.5.0 I get a crash on exit on the OculusViewerExample application, as well as on other apps I'm using the library with.
My config is:
- win 10
- VisualStudio 2013
- Oculus SDK 1.5.0
- osgOculusViewer rev 8d7e555a5cfc690127f3e520399e08f3a39f4070

I don't know if this is related somehow to https://github.com/bjornblissing/osgoculusviewer/issues/49

**Comment by bjornblissing** [comment]
Strange! I was not able to get this behavior even though I tried.

I have just pushed a special feature branch which tries to remedy these issues. Would you mind trying it out? It can be found here:
https://github.com/bjornblissing/osgoculusviewer/tree/feature/CleanupOnExit

Note that this branch requires you to compile against the current master of OpenSceneGraph. Since the required cleanupOperation have not been merged to any stable branch yet.

**Comment by rickyviking** [comment]
I have investigated a bit further and it turns out it was a **driver** issue. 
I've updated nVidia driver to 368.39 and the crash went away.
I've haven't tested your patch then, cannot comment on it atm.
