### ISSUE TITLE
Problem: assemble FlightGear on SDK

### ISSUE THREAD

**Issue by sczhaoyu** [bjornblissing/osgoculusviewer#90]
When I'm assembling FlightFear on SDK, the picture appeared to be a slight tilted. The users of FlightFear are still craving to solve this problem.
Our project only needs this last step to finish the work. 

https://sourceforge.net/projects/flightgear/

**Comment by bjornblissing** [comment]
Hi @sczhaoyu 

There are two problems with your issue:

### 1
FlightGear uses the GPLv2 license, so linking the Oculus SDK with FlightGear would probably be a violation against the license. Since the Oculus license is not GPL compatible. If the FlightGear community desire to use the Oculus SDK they would be forced to release FlightGear under a more permissive license.

See here for further information:

- https://github.com/bjornblissing/osgoculusviewer/issues/71
- https://forums.oculus.com/viewtopic.php?t=487

### 2
Your problem description is way to broad and leave many questions:

- What do you mean with "picture appeared to be a slight tilted"? 
- What hardware are you testing this on? 
- Have you tried multiple HMDs (DK2, CV1)? 
- Have you tried resetting the orientation of the HMD? (https://github.com/bjornblissing/osgoculusviewer/blob/4ed41f39b57d824d0f5c8f337449244684fb1fca/src/oculusdevice.h#L146) 
- _etc.. etc.._

**Comment by sczhaoyu** [comment]
@bjornblissing:
   My problem is to solve thank you。
